CREATE DATABASE maria;
USE maria;

CREATE TABLE IF NOT EXISTS `canal` (
  `ID_CANAL` INT NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_CANAL`),
  UNIQUE INDEX `ID_CANAL_UNIQUE` (`ID_CANAL` ASC) VISIBLE,
  UNIQUE INDEX `DESCRICAO_UNIQUE` (`DESCRICAO` ASC) VISIBLE);

CREATE TABLE IF NOT EXISTS `familia_comercial` (
  `COD_FAMILIA_COMERCIAL` INT NOT NULL AUTO_INCREMENT,
  `NOME_FAMILIA_COMERCIAL` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`COD_FAMILIA_COMERCIAL`),
  UNIQUE INDEX `COD_FAMILIA_COMERCIAL_UNIQUE` (`COD_FAMILIA_COMERCIAL` ASC) VISIBLE,
  UNIQUE INDEX `NOME_FAMILIA_COMERCIAL_UNIQUE` (`NOME_FAMILIA_COMERCIAL` ASC) VISIBLE);
  
  CREATE TABLE IF NOT EXISTS `produto` (
  `NOME_PRODUTO` VARCHAR(255) NOT NULL,
  `SKU` INT NOT NULL,
  `COD_FAMILIA_COMERCIAL` INT NOT NULL,
  PRIMARY KEY (`SKU`),
  UNIQUE INDEX `SKU_UNIQUE` (`SKU` ASC) VISIBLE,
  INDEX `fk_produto_familia_comercial1_idx` (`COD_FAMILIA_COMERCIAL` ASC) VISIBLE,
  CONSTRAINT `fk_produto_familia_comercial1`
    FOREIGN KEY (`COD_FAMILIA_COMERCIAL`)
    REFERENCES `familia_comercial` (`COD_FAMILIA_COMERCIAL`));
    
CREATE TABLE IF NOT EXISTS `sku_phase` (
  `SKU_PHASE_IN` INT NOT NULL,
  `SKU_PHASE_OUT` INT NOT NULL,
  INDEX `fk_sku_phase_produto3_idx` (`SKU_PHASE_IN` ASC) VISIBLE,
  INDEX `fk_sku_phase_produto4_idx` (`SKU_PHASE_OUT` ASC) VISIBLE,
  PRIMARY KEY (`SKU_PHASE_OUT`, `SKU_PHASE_IN`),
  CONSTRAINT `fk_sku_phase_produto3`
    FOREIGN KEY (`SKU_PHASE_IN`)
    REFERENCES `produto` (`SKU`),
  CONSTRAINT `fk_sku_phase_produto4`
    FOREIGN KEY (`SKU_PHASE_OUT`)
    REFERENCES `produto` (`SKU`));

CREATE TABLE IF NOT EXISTS `historico` (
  `MES_ANO` DATE NOT NULL,
  `QUANTIDADE` DECIMAL(10,3) NOT NULL DEFAULT 0,
  `PRODUTO_SKU` INT NOT NULL,
  `ID_CANAL` INT NOT NULL,
  PRIMARY KEY (`MES_ANO`, `ID_CANAL`, `PRODUTO_SKU`),
  INDEX `fk_historico_produto_idx` (`PRODUTO_SKU` ASC) VISIBLE,
  INDEX `fk_historico_canal1_idx` (`ID_CANAL` ASC) VISIBLE,
  CONSTRAINT `fk_historico_produto`
    FOREIGN KEY (`PRODUTO_SKU`)
    REFERENCES `produto` (`SKU`),
  CONSTRAINT `fk_historico_canal1`
    FOREIGN KEY (`ID_CANAL`)
    REFERENCES `canal` (`ID_CANAL`));